hw_info:
  cpu_id: ""
  cpu_name: ck802
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ""
  flash_program: ""
def_config:
  CONFIG_KERNEL_NONE: 1
  CONFIG_XIP: 1
  DBG_PRINT2PC: 1
  IS_CHIP_1104: 1
name: demo
version: v2.0.0
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - apt32f110x_demo: v2.0.0
  - sdk_110x: v2.0.0
build_config:
  include:
    - include
    - ./
  internal_include: 
  cflag: -Og  -g  -Wall  -ffunction-sections
  cxxflag: -Og  -g  -Wall  -ffunction-sections
  asmflag: -Wa,--gdwarf2
  define: 
  libs: 
  libpath: 
source_file:
  - src/*.c
depends_forward:
  - apt32f110x_demo: v2.0.0
  - sdk_110x: v2.0.0
install: 
homepage: 