/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "csi_drv.h"


void pin_init(void)
{
	csi_pin_drive(PA06,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA06,GPIO_PULLNONE);
	csi_pin_set_mux(PA06,PA06_GPD);
	csi_pin_output_mode(PA06,GPIO_PUSH_PULL);

	csi_pin_drive(PA07,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA07,GPIO_PULLNONE);
	csi_pin_set_mux(PA07,PA07_GPD);
	csi_pin_output_mode(PA07,GPIO_PUSH_PULL);

	csi_pin_drive(PA08,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA08,GPIO_PULLNONE);
	csi_pin_set_mux(PA08,PA08_GPD);
	csi_pin_output_mode(PA08,GPIO_PUSH_PULL);

	csi_pin_drive(PA09,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA09,GPIO_PULLNONE);
	csi_pin_set_mux(PA09,PA09_GPD);
	csi_pin_output_mode(PA09,GPIO_PUSH_PULL);

	csi_pin_drive(PA010,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA010,GPIO_PULLNONE);
	csi_pin_set_mux(PA010,PA010_GPD);
	csi_pin_output_mode(PA010,GPIO_PUSH_PULL);

	csi_pin_drive(PA011,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA011,GPIO_PULLNONE);
	csi_pin_set_mux(PA011,PA011_GPD);
	csi_pin_output_mode(PA011,GPIO_PUSH_PULL);

	csi_pin_drive(PA012,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA012,GPIO_PULLNONE);
	csi_pin_set_mux(PA012,PA012_GPD);
	csi_pin_output_mode(PA012,GPIO_PUSH_PULL);

	csi_pin_drive(PA013,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA013,GPIO_PULLNONE);
	csi_pin_set_mux(PA013,PA013_GPD);
	csi_pin_output_mode(PA013,GPIO_PUSH_PULL);

	csi_pin_drive(PA014,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA014,GPIO_PULLNONE);
	csi_pin_set_mux(PA014,PA014_GPD);
	csi_pin_output_mode(PA014,GPIO_PUSH_PULL);

	csi_pin_drive(PA015,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA015,GPIO_PULLNONE);
	csi_pin_set_mux(PA015,PA015_GPD);
	csi_pin_output_mode(PA015,GPIO_PUSH_PULL);

	csi_pin_drive(PB03,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB03,GPIO_PULLNONE);
	csi_pin_set_mux(PB03,PB03_GPD);
	csi_pin_output_mode(PB03,GPIO_PUSH_PULL);

	csi_pin_drive(PC01,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PC01,GPIO_PULLNONE);
	csi_pin_set_mux(PC01,PC01_GPD);
	csi_pin_output_mode(PC01,GPIO_PUSH_PULL);

	csi_pin_drive(PB04,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB04,GPIO_PULLNONE);
	csi_pin_set_mux(PB04,PB04_GPD);
	csi_pin_output_mode(PB04,GPIO_PUSH_PULL);

	csi_pin_drive(PA10,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA10,GPIO_PULLNONE);
	csi_pin_set_mux(PA10,PA10_GPD);
	csi_pin_output_mode(PA10,GPIO_PUSH_PULL);

	csi_pin_drive(PA11,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA11,GPIO_PULLNONE);
	csi_pin_set_mux(PA11,PA11_GPD);
	csi_pin_output_mode(PA11,GPIO_PUSH_PULL);

	csi_pin_drive(PA12,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA12,GPIO_PULLNONE);
	csi_pin_set_mux(PA12,PA12_GPD);
	csi_pin_output_mode(PA12,GPIO_PUSH_PULL);

	csi_pin_drive(PA13,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA13,GPIO_PULLNONE);
	csi_pin_set_mux(PA13,PA13_GPD);
	csi_pin_output_mode(PA13,GPIO_PUSH_PULL);

	csi_pin_drive(PA14,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA14,GPIO_PULLNONE);
	csi_pin_set_mux(PA14,PA14_GPD);
	csi_pin_output_mode(PA14,GPIO_PUSH_PULL);

	csi_pin_drive(PA15,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA15,GPIO_PULLNONE);
	csi_pin_set_mux(PA15,PA15_GPD);
	csi_pin_output_mode(PA15,GPIO_PUSH_PULL);

	csi_pin_drive(PA16,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA16,GPIO_PULLNONE);
	csi_pin_set_mux(PA16,PA16_GPD);
	csi_pin_output_mode(PA16,GPIO_PUSH_PULL);

	csi_pin_drive(PB05,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB05,GPIO_PULLNONE);
	csi_pin_set_mux(PB05,PB05_GPD);
	csi_pin_output_mode(PB05,GPIO_PUSH_PULL);

	csi_pin_drive(PA17,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA17,GPIO_PULLNONE);
	csi_pin_set_mux(PA17,PA17_GPD);
	csi_pin_output_mode(PA17,GPIO_PUSH_PULL);

	csi_pin_drive(PB06,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB06,GPIO_PULLNONE);
	csi_pin_set_mux(PB06,PB06_GPD);
	csi_pin_output_mode(PB06,GPIO_PUSH_PULL);

	csi_pin_drive(PB07,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB07,GPIO_PULLNONE);
	csi_pin_set_mux(PB07,PB07_GPD);
	csi_pin_output_mode(PB07,GPIO_PUSH_PULL);

	csi_pin_drive(PA18,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA18,GPIO_PULLNONE);
	csi_pin_set_mux(PA18,PA18_GPD);
	csi_pin_output_mode(PA18,GPIO_PUSH_PULL);

	csi_pin_drive(PB08,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB08,GPIO_PULLNONE);
	csi_pin_set_mux(PB08,PB08_GPD);
	csi_pin_output_mode(PB08,GPIO_PUSH_PULL);

	csi_pin_drive(PB09,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB09,GPIO_PULLNONE);
	csi_pin_set_mux(PB09,PB09_GPD);
	csi_pin_output_mode(PB09,GPIO_PUSH_PULL);

	csi_pin_drive(PB010,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB010,GPIO_PULLNONE);
	csi_pin_set_mux(PB010,PB010_GPD);
	csi_pin_output_mode(PB010,GPIO_PUSH_PULL);

	csi_pin_drive(PB011,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB011,GPIO_PULLNONE);
	csi_pin_set_mux(PB011,PB011_GPD);
	csi_pin_output_mode(PB011,GPIO_PUSH_PULL);

	csi_pin_drive(PA19,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA19,GPIO_PULLNONE);
	csi_pin_set_mux(PA19,PA19_GPD);
	csi_pin_output_mode(PA19,GPIO_PUSH_PULL);

	csi_pin_drive(PA110,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA110,GPIO_PULLNONE);
	csi_pin_set_mux(PA110,PA110_GPD);
	csi_pin_output_mode(PA110,GPIO_PUSH_PULL);

	csi_pin_drive(PA111,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA111,GPIO_PULLNONE);
	csi_pin_set_mux(PA111,PA111_GPD);
	csi_pin_output_mode(PA111,GPIO_PUSH_PULL);

	csi_pin_drive(PA112,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA112,GPIO_PULLNONE);
	csi_pin_set_mux(PA112,PA112_GPD);
	csi_pin_output_mode(PA112,GPIO_PUSH_PULL);

	csi_pin_drive(PA113,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA113,GPIO_PULLNONE);
	csi_pin_set_mux(PA113,PA113_GPD);
	csi_pin_output_mode(PA113,GPIO_PUSH_PULL);

	csi_pin_drive(PC00,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PC00,GPIO_PULLNONE);
	csi_pin_set_mux(PC00,PC00_GPD);
	csi_pin_output_mode(PC00,GPIO_PUSH_PULL);

	csi_pin_drive(PA00,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA00,GPIO_PULLNONE);
	csi_pin_set_mux(PA00,PA00_GPD);
	csi_pin_output_mode(PA00,GPIO_PUSH_PULL);

	csi_pin_drive(PA01,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA01,GPIO_PULLNONE);
	csi_pin_set_mux(PA01,PA01_GPD);
	csi_pin_output_mode(PA01,GPIO_PUSH_PULL);

	csi_pin_drive(PA02,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA02,GPIO_PULLNONE);
	csi_pin_set_mux(PA02,PA02_GPD);
	csi_pin_output_mode(PA02,GPIO_PUSH_PULL);

	csi_pin_drive(PA03,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA03,GPIO_PULLNONE);
	csi_pin_set_mux(PA03,PA03_GPD);
	csi_pin_output_mode(PA03,GPIO_PUSH_PULL);

	csi_pin_drive(PA04,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA04,GPIO_PULLNONE);
	csi_pin_set_mux(PA04,PA04_GPD);
	csi_pin_output_mode(PA04,GPIO_PUSH_PULL);

	csi_pin_drive(PA05,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PA05,GPIO_PULLNONE);
	csi_pin_set_mux(PA05,PA05_GPD);
	csi_pin_output_mode(PA05,GPIO_PUSH_PULL);

	csi_pin_drive(PB00,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB00,GPIO_PULLNONE);
	csi_pin_set_mux(PB00,PB00_GPD);
	csi_pin_output_mode(PB00,GPIO_PUSH_PULL);

	csi_pin_drive(PB01,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB01,GPIO_PULLNONE);
	csi_pin_set_mux(PB01,PB01_GPD);
	csi_pin_output_mode(PB01,GPIO_PUSH_PULL);

	csi_pin_drive(PB02,GPIO_DRIVE_LV0);
	csi_pin_pull_mode(PB02,GPIO_PULLNONE);
	csi_pin_set_mux(PB02,PB02_GPD);
	csi_pin_output_mode(PB02,GPIO_PUSH_PULL);

}

void adc_init(void)
{
}

void sysclock_init(void)
{
	csi_clk_config_t tClkConfig = { SRC_HFOSC, HFOSC_48M_VALUE, SCLK_DIV1, PCLK_DIV2, 5556000, 5556000 };
	csi_sysclk_config(tClkConfig);
}

void __attribute__ ((weak)) __ChipInitHandler(void)
{
    pin_init();
    adc_init();
    sysclock_init();
}
