/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "csi_drv.h"


void pin_init(void)
{
		Driving Ability : "Normal"
		IOFunctions : "High_Z"
		Pull Mode : "Pull_None"
		pinNum : "38"
}

void ch0_config(void)
{
}

void adc_init(void)
{
}

void __attribute__ ((weak)) __ChipInitHandler(void)
{
    pin_init();
    ch0_config();
    adc_init();
}
