/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "csi_drv.h"


void pin_init(void)
{
}

void adc_init(void)
{
}

void __attribute__ ((weak)) __ChipInitHandler(void)
{
    pin_init();
    adc_init();
}
