/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "soc.h"
#include "drv/gpio.h"
#include "drv/pin.h"


void PinConfigInit(void)
{
	csi_pin_set_mux(PA06,PA06_OUTPUT);
	csi_pin_set_mux(PA07,PA07_OUTPUT);
	csi_pin_pull_mode(PA07,GPIO_PULLUP);

	csi_pin_set_mux(PA010,PA010_ADC_AIN10);
}

void __attribute__ ((weak)) __ChipInitHandler(void)
{
    PinConfigInit();
}
